version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: filmosearchportal-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: FilmoSearchPortal
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
  #hardcore connection:(